### PR TITLE
get images from psn store

### PR DESCRIPTION
**Pull request by eracknaphobia**
Added the ability to attempt to pull the image from the playstation store.

### CODE REVIEW

**Comment by hmn** [comment]
it looks like there is an error with encode

2018-01-05 20:18:59 ERROR (MainThread) [custom_components.media_player.ps4] could not retrieve cover art, 'NoneType' object has no attribute 'encode'

**Comment by eracknaphobia** [comment]
Hmm, self._media_title should be set by the time this is called because the function is not called until a game / app is running. Do you any more info on how you got this error to occur?

**Comment by hmn** [comment]
I think it's if you have had the ps4 closed and no application is started, then it returns None in media title

**Comment by eracknaphobia** [comment]
Ah, ok. I will fix a resubmit.

**Comment by hmn** [comment]
as far as I can see you are also doing the complete call on each update, so that probably also needs to be fixed so we don't do a search every 30 seconds

**Comment by eracknaphobia** [comment]
Yeah, I wasn't sure how that worked. So I assume we could store the image url into a variable.

**Comment by hmn** [comment]
I think it would make sense to add the url to the gamesmap if it is missing, and then only search for a new image if it is missing

then the media_image_url should just return the url

**Comment by hmn** [comment]
as far as I remember entity_picture should only be used for local images, so I think the solution would be to move the run of psn_cover_art into the update function and change it to be an update function for adding url's to the gamesmap, then it should cache pictures and still work for new stuff and any missing stuff in the store could be mapped via the json file either locally or via the remote file

**Comment by eracknaphobia** [comment]
Yes, I think I follow what you are saying. I'll give it a go and see what I can work out. Thanks for the prompt responses.

**Pull request merged**
