### PR TITLE
Ps4 component using pyps4

### PR DESCRIPTION
**Pull request by hthiery**
I used your original ps4 component from your home-assistant branch and did some modifications. Hope your're ok with this. With having a custom_component at this point I think it is easier to share modifications before it is ready for upstreaming.

### CODE REVIEW

**Comment by hmn** [comment]
Getting status seems to work fine, but turning the ps4 on or off fails

this is what I get when trying to switch the ps4 off :
`2018-02-06 15:02:24 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall media_player.turn_off: entity_id=['media_player.playstation_4']>
Traceback (most recent call last):
  File "/config/deps/lib/python3.6/site-packages/construct/core.py", line 2384, in _build
    return self.subcon._build(obj, stream, context, path)
  File "/config/deps/lib/python3.6/site-packages/construct/core.py", line 745, in _build
    _write_stream(stream, length, data)
  File "/config/deps/lib/python3.6/site-packages/construct/core.py", line 85, in _write_stream
    raise StreamError("could not write bytes, expected %d, found %d" % (length, len(data)))
construct.core.StreamError: could not write bytes, expected 64, found 120

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    yield from service_handler.func(service_call)
  File "/usr/src/app/homeassistant/components/media_player/__init__.py", line 402, in async_service_handler
    yield from getattr(player, method['method'])(**params)
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 327, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/ps4.py", line 347, in turn_off
    self.ps4.standby()
  File "/config/deps/lib/python3.6/site-packages/pyps4/ps4.py", line 90, in standby
    self._connection.login()
  File "/config/deps/lib/python3.6/site-packages/pyps4/connection.py", line 63, in login
  File "/config/deps/lib/python3.6/site-packages/pyps4/connection.py", line 168, in _send_login_request
    msg = fmt.build(config)
    self.build_stream(obj, stream, **kw)
  File "/config/deps/lib/python3.6/site-packages/construct/core.py", line 294, in build_stream
  File "/config/deps/lib/python3.6/site-packages/construct/core.py", line 1895, in _build
    buildret = sc._build(subobj, stream, context, path)
    raise e.__class__("%s\n    %s" % (e, path))
construct.core.StreamError: could not write bytes, expected 64, found 120
`

**Comment by hthiery** [comment]
could you please check what version of construct is installed?

`pip show construct`

**Comment by hmn** [comment]
i'm running in docker, so it should be pretty standard

```
root@alladin:/usr/src/app# pip show construct
Name: construct
Version: 2.9.24
Summary: A powerful declarative parser/builder for binary data
Home-page: http://construct.readthedocs.org
Author: Arkadiusz Bulski, Tomer Filiba, Corbin Simpson
Author-email: arek.bulski@gmail.com, tomerfiliba@gmail.com, MostAwesomeDude@gmail.com
License: MIT
Location: /usr/local/lib/python3.6/site-packages
Requires: 
```

**Comment by hthiery** [comment]
I use the following:
> Name: construct
> Version: 2.9.26
> Summary: A powerful declarative parser/builder for binary data
> Home-page: http://construct.readthedocs.org
> Author: Arkadiusz Bulski, Tomer Filiba, Corbin Simpson
> Author-email: arek.bulski@gmail.com, tomerfiliba@gmail.com, MostAwesomeDude@gmail.com
> License: MIT
> Location: /srv/homeassistant/lib/python3.5/site-packages
> Requires: 
>

**Comment by hmn** [comment]
but if 2.9.26 is required should it not be defined in the package?

**Comment by hthiery** [comment]
i dont know exactly if this is the problem. but if it is yes it should. But then I think to remove the dependency to construct.

**Comment by hmn** [comment]
I can try updating my docker image and see if it changes anything

**Comment by hmn** [comment]
I tried upgrading it to 2.9.27 but the problem still persists

Mmaybe try adding some debug with the packages you send. It looks like the status requests work fine but the wakeup command is somehow not recognized by the ps4 (used tcpdump to verify that it is being sent)

**Comment by hmn** [comment]
I found the problem, I think you changed the way the credentials are suppose to be entered from pasting the full json to just the credentials token

when I added only the token it works.

**Comment by hthiery** [comment]
oh ...ok ... we should properly check the correct format

**Comment by hmn** [comment]
yes, but I think it would be better to have a check/login command I can use in the configure function, so we verify that it can actually talk to the ps4 with the credentials

**Comment by hthiery** [comment]
sorry for beeing silent in the last 2 weeks ... 

any suggestions how to process now with the move to the python lib?

**Comment by hmn** [comment]
I have been moving my setup to hass.io as it seems like this is the way most people will be running it, and currently I can't seem to get the custom component to load, so I think we should make the initial load more stable.

and figure out how to handle any errors in registration so if you enter wrong credentials it does not save it an continue

I don't know how you run it, but have you had any problems loading the module? because I started getting these errors on my hass.io setup

```
2018-02-15 16:17:01 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform ps4
Traceback (most recent call last):                                                                             
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 84, in async_setup                  
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)                                                                                   
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for                                                            
    return fut.result()                                                                                                
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result                                                        
    raise self._exception                                                    
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run                                      
    result = self.fn(*self.args, **self.kwargs)                                                                        
  File "/config/custom_components/media_player/ps4.py", line 177, in setup_platform                                                
    config, add_devices, credentials)                                                                                                    
  File "/config/custom_components/media_player/ps4.py", line 86, in setup_ps4                                                                      
    import pyps4                                                                                                                 
  File "/config/deps/lib/python3.6/site-packages/pyps4/__init__.py", line 2, in <module>                 
    from .connection import *                                                                                      
  File "/config/deps/lib/python3.6/site-packages/pyps4/connection.py", line 9, in <module>                     
    from Crypto.Cipher import AES, PKCS1_OAEP                                                                            
  File "/usr/lib/python3.6/site-packages/Crypto/Cipher/PKCS1_OAEP.py", line 57, in <module>                                            
    import Crypto.Signature.PKCS1_PSS                                                                                                
  File "/usr/lib/python3.6/site-packages/Crypto/Signature/PKCS1_PSS.py", line 70, in <module>                                    
    if sys.version_info[0] == 2 and sys.version_info[1] == 1:                                                                              
NameError: name 'sys' is not defined                                                                                           
2018-02-15 16:17:01 INFO (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: timestamp=1518707821.7348812, level=ERROR, message=Error while setting up platform ps4, exception=Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 84, in async_setup
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)                                    
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for                                          
    return fut.result()                                                                                    
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result                                                        
    raise self._exception                                                          
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run                                                                             
    result = self.fn(*self.args, **self.kwargs)                                                                                                        
  File "/config/custom_components/media_player/ps4.py", line 177, in setup_platform                       
    config, add_devices, credentials)                                                                                      
  File "/config/custom_components/media_player/ps4.py", line 86, in setup_ps4                                                
    import pyps4                                                                                                                       
  File "/config/deps/lib/python3.6/site-packages/pyps4/__init__.py", line 2, in <module>                                               
    from .connection import *                                                                                                          
  File "/config/deps/lib/python3.6/site-packages/pyps4/connection.py", line 9, in <module>                                               
    from Crypto.Cipher import AES, PKCS1_OAEP                                                                                          
  File "/usr/lib/python3.6/site-packages/Crypto/Cipher/PKCS1_OAEP.py", line 57, in <module>
    import Crypto.Signature.PKCS1_PSS                                                                                                                                                                                                                                            
  File "/usr/lib/python3.6/site-packages/Crypto/Signature/PKCS1_PSS.py", line 70, in <module>                                                                                                                                                                                    
    if sys.version_info[0] == 2 and sys.version_info[1] == 1:                                                                                                                                                                                                                    
NameError: name 'sys' is not defined                                                                                                                                                                                                                                             
, source=deps/lib/python3.6/site-packages/pyps4/connection.py>                                       
```

**Comment by hthiery** [comment]
I installed home-assistant in an virtual env on my home server. And unfortunatly I didn't see the failures you see.

For the check for connection or check for the credential I will prepare something and let you know.

**Pull request merged**
